### ISSUE TITLE
Footer now showing

### ISSUE THREAD

**Issue by vg0426** [orhanobut/dialogplus#136] opened 2017-07-09 16:30 UTC
Hi am trying your library and it looks really nice till i tried to set a footer view and is not showing on the dialog, I've added a a header and a content views and everything is showing but the footer. Can someone advice, please. Thanks

**Comment by mikaere66** [comment] 2017-07-10 16:11
I use DialogPlus in one of my projects, and have it working perfectly ... here is the code snippet :
public void showInstructions(@SuppressWarnings("UnusedParameters") View view) {
    List instructions = DirectionsJSONParser.getInstructions();
    List<Spanned> html = new ArrayList<>();
    for (Object instruction : instructions) {
        html.add(Common.fromHtml(instruction.toString()));
    }
    // Dialog content
    DialogPlus dialogPlus = DialogPlus.newDialog(this)
            .setAdapter(new ArrayAdapter<>(this, android.R.layout.simple_list_item_1, html))
            .setCancelable(true)
            .setHeader(R.layout.html_header_layout)
            .setFooter(R.layout.html_footer_layout)
            .create();
    // Dialog header
    String summary = DirectionsJSONParser.getSummary();
    if (!summary.equals("")) {
        String title = getString(R.string.summary) + " " + DirectionsJSONParser.getSummary();
        TextView htmlHeader = (TextView) dialogPlus.findViewById(R.id.html_header);
        if (!fullScreen && myAB != null) {
            myAB.setSubtitle(title);
            htmlHeader.setVisibility(View.GONE);
        } else {
            htmlHeader.setText(title);
        }
    }
    // Dialog footer (warning as per Google guidelines)
    TextView htmlFooter = (TextView) dialogPlus.findViewById(R.id.html_footer);
    String warning = DirectionsJSONParser.getWarning();
    if (warning.length() > 0) {
        htmlFooter.setText(warning);
    } else {
        htmlFooter.setVisibility(View.GONE);
    }
    dialogPlus.show();
}

**Comment by orhanobut** [comment] 2018-04-09 13:04
Closing this one, I suppose the issue is solved hopefully. If not, we can reopen.

**Closed by orhanobut** 2018-04-09 13:04 UTC
