### ISSUE TITLE
setOnItemClick not working 

### ISSUE THREAD

**Issue by AndroidLTG** [orhanobut/dialogplus#96] opened 2016-01-18 04:27 UTC
I use a adapter String and create dialoe but when setOnItemClick then nothing happens.
This is my  code:
 ArrayAdapter<String> dialogOrder = new ArrayAdapter<>(getContext(), R.layout.dialog_menu_custom);

```
            dialogOrder.add(getString(R.string.check_in));
            dialogOrder.add(getString(R.string.check_out));
            dialogOrder.add(getString(R.string.cancel));
            Home.dialogOrder = DialogPlus.newDialog(getContext())
                    .setAdapter(dialogOrder)
                    .setOnItemClickListener(new OnItemClickListener() {
                        @Override
                        public void onItemClick(DialogPlus dialog, Object item, View view, int position) {
                            MyMethod.showToast(getContext(), "CUSTOMER");
                        }
                    })
                    .setHeader(R.layout.header_dialog)
                    .setFooter(R.layout.footer_dialog)
                    .setExpanded(false)  // This will enable the expand feature, (similar to android L share dialog)
                    .create();
            Home.dialogOrder.findViewById(R.id.footer_dialog).requestFocus();
            Home.dialogOrder.show();
```

**Comment by orhanobut** [comment] 2016-01-29 23:08
everything seems definitely fine. let me try the same thing as you did in weekend.

**Comment by orhanobut** [comment] 2016-01-31 14:52
still cannot reproduce this issue.

**Comment by orhanobut** [comment] 2018-04-09 13:18
Closing this issue due to long time period, can reopen if needed

**Closed by orhanobut** 2018-04-09 13:18 UTC
